# Use the official Golang image as a base image
FROM golang:1.20

# Set the working directory
WORKDIR /app

# Copy the go.mod and go.sum files to the workspace
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the rest of the application code to the workspace
COPY . .

# Expose the application port (adjust the port according to your application)
EXPOSE 8080

# Command to start the application with reflex for live reloading
CMD ["reflex", "-r", "\\.go$", "--", "go", "run", "main.go"]


# in you docker compose, do
# volumes:
#    - .:/app
# ports:
#    - "8080:8080"
# command: reflex -r '\.go$' -- go run main.go