version: '3.8'
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - gomod_cache:/go/pkg/mod
      - gocache_build:/root/.cache/go-build
    ports:
      - "8080:8080"
    command: reflex -r '\\.go$' -- go run main.go

volumes:
  gomod_cache:
  gocache_build: