FROM node:19.4-bullseye as build
# (or) FROM node:19.4-bullseye-slim as build

RUN addgroup app && adduser -S -G app app
USER app

WORKDIR /usr/src/app

COPY --chown=app:app package.json pnpm-lock.yaml ./

RUN npm i -g pnpm

# ensure to set the volumes for the pnpm store
RUN pnpm set store-dir /usr/src/app/.pnpm-store && pnpm install

COPY --chown=app:app . ./
# (or) COPY . ./; RUN chown -R app:app ./ 

EXPOSE 3000

ENV DB_PORT=5432 \
    DB_URL=https://mongodb.com/connect \
    DB_PASSWORD=secret

CMD ["pnpm", "run", "dev"]
# (or) CMD ["pnpm", "run", "start"]